// example-projects/svelte-example/src/App.svelte
<script lang="ts">
  import Tightset from 'tightset/svelte'
  import { onMount } from 'svelte'

  let text = 'Every Line Fills The Width'
  let fontsReady = false

  onMount(() => {
    document.fonts.ready.then(() => { fontsReady = true })
  })
</script>

<div style="min-height: 100vh; background: #0a0a0a; color: #fff; font-family: Inter, sans-serif; display: flex; flex-direction: column; align-items: center; padding: 2rem; gap: 2rem;">
  <div style="display: flex; align-items: center; gap: 0.75rem;">
    <svg viewBox="0 0 400 400" width="40" height="40"><rect x="16" y="16" width="368" height="368" rx="32" fill="#0a0a0a" stroke="#333" stroke-width="2"/><text x="200" y="168" text-anchor="middle" font-family="Inter, system-ui, sans-serif" font-size="107" font-weight="700" fill="#ffffff" letter-spacing="-0.03em">TIGHT</text><text x="200" y="308" text-anchor="middle" font-family="Inter, system-ui, sans-serif" font-size="172" font-weight="900" fill="#ffffff" letter-spacing="-0.03em">SET</text></svg>
    <span style="font-size: 1.5rem; font-weight: 300; color: #555;">×</span>
    <svg viewBox="0 0 24 24" width="36" height="36" fill="#FF3E00"><path d="M10.354 21.125a4.44 4.44 0 0 1-4.765-1.767 4.109 4.109 0 0 1-.703-3.107 3.898 3.898 0 0 1 .134-.522l.105-.321.287.21a7.21 7.21 0 0 0 2.186 1.092l.208.063-.02.208a1.253 1.253 0 0 0 .226.83 1.337 1.337 0 0 0 1.435.533 1.231 1.231 0 0 0 .343-.15l5.59-3.562a1.164 1.164 0 0 0 .524-.778 1.242 1.242 0 0 0-.211-.937 1.338 1.338 0 0 0-1.435-.533 1.23 1.23 0 0 0-.343.15l-2.133 1.36a4.078 4.078 0 0 1-1.135.499 4.44 4.44 0 0 1-4.765-1.766 4.108 4.108 0 0 1-.702-3.108 3.855 3.855 0 0 1 1.742-2.582l5.589-3.563a4.072 4.072 0 0 1 1.135-.499 4.44 4.44 0 0 1 4.765 1.767 4.109 4.109 0 0 1 .703 3.107 3.943 3.943 0 0 1-.134.522l-.105.321-.286-.21a7.204 7.204 0 0 0-2.187-1.093l-.208-.063.02-.207a1.255 1.255 0 0 0-.226-.831 1.337 1.337 0 0 0-1.435-.532 1.231 1.231 0 0 0-.343.15L8.62 9.368a1.162 1.162 0 0 0-.524.778 1.24 1.24 0 0 0 .211.937 1.338 1.338 0 0 0 1.435.533 1.235 1.235 0 0 0 .344-.151l2.132-1.36a4.067 4.067 0 0 1 1.135-.498 4.44 4.44 0 0 1 4.765 1.766 4.108 4.108 0 0 1 .702 3.108 3.857 3.857 0 0 1-1.742 2.583l-5.589 3.562a4.072 4.072 0 0 1-1.135.499m10.358-17.95C18.484-.015 14.082-.96 10.9 1.068L5.31 4.63a6.412 6.412 0 0 0-2.896 4.295 6.753 6.753 0 0 0 .666 4.336 6.43 6.43 0 0 0-.96 2.396 6.833 6.833 0 0 0 1.168 5.167c2.229 3.19 6.63 4.135 9.812 2.108l5.59-3.562a6.41 6.41 0 0 0 2.896-4.295 6.756 6.756 0 0 0-.665-4.336 6.429 6.429 0 0 0 .958-2.396 6.831 6.831 0 0 0-1.167-5.168Z"/></svg>
    <h1 style="font-weight: 300; color: #666; margin: 0;">Svelte</h1>
  </div>
  <input
    bind:value={text}
    style="width: 400px; padding: 0.5rem 1rem; border-radius: 8px; border: 1px solid #333; background: #111; color: #fff; font-size: 1rem; font-family: inherit;"
  />
  {#if fontsReady}
    <Tightset
      {text}
      width={800}
      height={400}
      fontFamily="Inter"
      color="#ffffff"
      background="#0d0d0d"
      maxWeight={900}
      spread={150}
    />
  {/if}
</div>

// example-projects/angular-example/src/app/app.ts
import { Component, signal } from '@angular/core';
import { TightsetComponent } from './tightset.component';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-root',
  imports: [TightsetComponent, FormsModule],
  template: `
    <div class="wrapper">
      <div class="header">
        <svg viewBox="0 0 400 400" width="40" height="40"><rect x="16" y="16" width="368" height="368" rx="32" fill="#0a0a0a" stroke="#333" stroke-width="2"/><text x="200" y="168" text-anchor="middle" font-family="Inter, system-ui, sans-serif" font-size="107" font-weight="700" fill="#ffffff" letter-spacing="-0.03em">TIGHT</text><text x="200" y="308" text-anchor="middle" font-family="Inter, system-ui, sans-serif" font-size="172" font-weight="900" fill="#ffffff" letter-spacing="-0.03em">SET</text></svg>
        <span class="sep">×</span>
        <svg viewBox="0 0 24 24" width="36" height="36" fill="#DD0031"><path d="M16.712 17.711H7.288l-1.204 2.916L12 24l5.916-3.373-1.204-2.916ZM14.692 0l7.832 16.855.814-12.856L14.692 0ZM9.308 0 .662 3.999l.814 12.856L9.308 0Zm-.405 13.93h6.198L12 6.396 8.903 13.93Z"/></svg>
        <h1>Angular</h1>
      </div>
      <input [(ngModel)]="text" />
      @if (fontsReady()) {
        <tightset
          [text]="text"
          [width]="800"
          [height]="400"
          fontFamily="Inter"
          color="#ffffff"
          background="#0d0d0d"
          [maxWeight]="900"
          [spread]="150"
        />
      }
    </div>
  `,
  styles: [`
    .wrapper {
      min-height: 100vh;
      background: #0a0a0a;
      color: #fff;
      font-family: Inter, sans-serif;
      display: flex;
      flex-direction: column;
      align-items: center;
      padding: 2rem;
      gap: 2rem;
    }
    .header {
      display: flex;
      align-items: center;
      gap: 0.75rem;
    }
    .sep { font-size: 1.5rem; font-weight: 300; color: #555; }
    h1 { font-weight: 300; color: #666; margin: 0; }
    input {
      width: 400px;
      padding: 0.5rem 1rem;
      border-radius: 8px;
      border: 1px solid #333;
      background: #111;
      color: #fff;
      font-size: 1rem;
      font-family: inherit;
    }
  `],
})
export class App {
  text = 'Every Line Fills The Width';
  fontsReady = signal(false);

  constructor() {
    document.fonts.ready.then(() => this.fontsReady.set(true));
  }
}
