// example-projects/angular-example/src/app/tightset.component.ts
/**
 * tightset/angular — Angular standalone component for variable-weight text fitting.
 *
 * Renders fitted text onto a <canvas> element. Requires Angular 16+ (standalone components).
 * Re-renders automatically when any input changes.
 *
 * @example
 * ```ts
 * import { TightsetComponent } from 'tightset/angular'
 *
 * @Component({
 *   standalone: true,
 *   imports: [TightsetComponent],
 *   template: `
 *     <tightset
 *       text="Every Line Fills The Width"
 *       [width]="800"
 *       [height]="500"
 *       fontFamily="Inter"
 *       color="#ffffff"
 *       background="#0d0d0d"
 *     />
 *   `,
 * })
 * export class MyComponent {}
 * ```
 *
 * @license MIT
 */

import {
  Component,
  input,
  output,
  viewChild,
  ElementRef,
  effect,
} from '@angular/core'
import { fit, type TightsetOptions, type FitResult } from 'tightset'
import { render as renderCanvas } from 'tightset/canvas'

@Component({
  selector: 'tightset',
  standalone: true,
  template: '<canvas #canvas [style.width.px]="width()" [style.height.px]="height()"></canvas>',
})
export class TightsetComponent {
  /** The text to fit */
  readonly text = input.required<string>()
  /** Canvas width in CSS pixels */
  readonly width = input.required<number>()
  /** Canvas height in CSS pixels */
  readonly height = input.required<number>()
  /** Font family (must be loaded; default: 'sans-serif') */
  readonly fontFamily = input<string>('sans-serif')
  /** Text color (default: '#ffffff') */
  readonly color = input<string>('#ffffff')
  /** Background color (default: undefined = transparent) */
  readonly background = input<string | undefined>(undefined)
  /** Max font weight (default: 900) */
  readonly maxWeight = input<number>(900)
  /** Weight spread between largest and smallest lines (default: 150) */
  readonly spread = input<number>(150)
  /** Horizontal padding (default: 60) */
  readonly padX = input<number>(60)
  /** Vertical padding (default: 40) */
  readonly padY = input<number>(40)
  /** Line gap in pixels (default: 20) */
  readonly gap = input<number>(20)
  /** Max lines (default: 8) */
  readonly maxLines = input<number>(8)
  /** Uppercase text (default: true) */
  readonly uppercase = input<boolean>(true)
  /** Device pixel ratio override */
  readonly dpr = input<number>(typeof window !== 'undefined' ? window.devicePixelRatio : 1)

  /** Emits the FitResult after each render (or null if fitting failed) */
  readonly fitResult = output<FitResult | null>()

  readonly canvasRef = viewChild.required<ElementRef<HTMLCanvasElement>>('canvas')

  constructor() {
    effect(() => {
      this.redraw()
    })
  }

  private redraw() {
    const canvas = this.canvasRef().nativeElement
    const text = this.text()
    if (!canvas || !text?.trim()) {
      this.fitResult.emit(null)
      return
    }

    const opts: TightsetOptions = {
      width: this.width(),
      height: this.height(),
      padX: this.padX(),
      padY: this.padY(),
      gap: this.gap(),
      maxWeight: this.maxWeight(),
      spread: this.spread(),
      maxLines: this.maxLines(),
      uppercase: this.uppercase(),
      fontFamily: this.fontFamily(),
    }

    const result = fit(text, opts)
    this.fitResult.emit(result)

    if (!result) return

    const dpr = this.dpr()
    canvas.width = Math.round(this.width() * dpr)
    canvas.height = Math.round(this.height() * dpr)
    renderCanvas(canvas, result, {
      fontFamily: this.fontFamily(),
      color: this.color(),
      background: this.background(),
      gap: this.gap(),
      padY: this.padY(),
      dpr,
    })
  }
}

export { fit, type FitResult, type TightsetOptions } from 'tightset'

// src/react/Tightset.tsx
/**
 * tightset/react — React component for variable-weight text fitting.
 *
 * @license MIT
 */

import { useRef, useEffect, useMemo, type CSSProperties } from 'react'
import { fit, clearCache, type TightsetOptions, type FitResult } from '../index'
import { render as renderCanvas } from '../canvas'

export interface TightsetProps {
  /** The text to fit */
  text: string
  /** Canvas width in CSS pixels */
  width: number
  /** Canvas height in CSS pixels */
  height: number
  /** Font family (must be loaded; default: 'sans-serif') */
  fontFamily?: string
  /** Text color (default: '#ffffff') */
  color?: string
  /** Background color (default: transparent) */
  background?: string
  /** Max font weight (default: 900) */
  maxWeight?: number
  /** Weight spread between largest and smallest lines (default: 150) */
  spread?: number
  /** Horizontal padding (default: 60) */
  padX?: number
  /** Vertical padding (default: 40) */
  padY?: number
  /** Line gap in pixels (default: 20) */
  gap?: number
  /** Max lines (default: 8) */
  maxLines?: number
  /** Uppercase text (default: true) */
  uppercase?: boolean
  /** Device pixel ratio override */
  dpr?: number
  /** Additional CSS class */
  className?: string
  /** Additional inline styles */
  style?: CSSProperties
  /** Callback with the fit result (for custom rendering) */
  onFit?: (result: FitResult | null) => void
}

/**
 * React component that renders variable-weight fitted text on a canvas.
 *
 * @example
 * ```tsx
 * import { Tightset } from 'tightset/react'
 *
 * function App() {
 *   return (
 *     <Tightset
 *       text="Every Line Fills The Width"
 *       width={800}
 *       height={500}
 *       fontFamily="Inter"
 *       color="#ffffff"
 *       background="#0d0d0d"
 *       maxWeight={900}
 *       spread={150}
 *     />
 *   )
 * }
 * ```
 */
export function Tightset({
  text,
  width,
  height,
  fontFamily = 'sans-serif',
  color = '#ffffff',
  background,
  maxWeight = 900,
  spread = 150,
  padX = 60,
  padY = 40,
  gap = 20,
  maxLines = 8,
  uppercase = true,
  dpr: dprProp,
  className,
  style,
  onFit,
}: TightsetProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const dpr = dprProp ?? (typeof window !== 'undefined' ? window.devicePixelRatio : 1)

  const opts: TightsetOptions = useMemo(() => ({
    width, height, padX, padY, gap,
    maxWeight, spread, maxLines, uppercase, fontFamily,
  }), [width, height, padX, padY, gap, maxWeight, spread, maxLines, uppercase, fontFamily])

  const result = useMemo(() => {
    if (!text.trim()) return null
    return fit(text, opts)
  }, [text, opts])

  useEffect(() => {
    onFit?.(result)
  }, [result, onFit])

  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas || !result) return
    canvas.width = Math.round(width * dpr)
    canvas.height = Math.round(height * dpr)
    renderCanvas(canvas, result, { fontFamily, color, background, gap, padY, dpr })
  }, [result, width, height, dpr, fontFamily, color, background, gap, padY])

  return (
    <canvas
      ref={canvasRef}
      width={Math.round(width * dpr)}
      height={Math.round(height * dpr)}
      className={className}
      style={{ width, height, ...style }}
    />
  )
}

export { fit, clearCache, type FitResult, type TightsetOptions } from '../index'
